package com.berkant.yaninda.ui.theme

import androidx.compose.ui.graphics.Color

internal val WarmBackground = Color(0xFFF3F7FB)
internal val WarmSurface = Color(0xFFFFFFFF)
internal val WarmSurfaceVariant = Color(0xFFEBF1F6)
internal val Ink = Color(0xFF101820)
internal val InkMuted = Color(0xFF4E5D69)
internal val DeepBlue = Color(0xFF096FAF)
internal val OnDeepBlue = Color(0xFFFFFFFF)
internal val PaleBlue = Color(0xFFDCEFFC)
internal val OnPaleBlue = Color(0xFF0B3855)
internal val WarmBrown = Color(0xFF174F73)
internal val OnWarmBrown = Color(0xFFFFFFFF)
internal val PaleSecondary = Color(0xFFE4F0F8)
internal val OnPaleSecondary = Color(0xFF17394F)
internal val SuccessGreen = Color(0xFF138A4B)
internal val OnSuccessGreen = Color(0xFFFFFFFF)
internal val PaleGreen = Color(0xFFDDF5E8)
internal val OnPaleGreen = Color(0xFF073D23)
internal val StrongOutline = Color(0xFF617483)
internal val SoftOutline = Color(0xFFD8E2EA)
internal val AlarmRust = Color(0xFFD52D3D)
internal val OnAlarmRust = Color(0xFFFFFFFF)
internal val PaleAlarm = Color(0xFFFDE7E9)
internal val OnPaleAlarm = Color(0xFF6F101C)
internal val WarningAmber = Color(0xFF9A5B00)
internal val PaleWarning = Color(0xFFFFEFC7)
internal val OnPaleWarning = Color(0xFF573400)

internal val NightBackground = Color(0xFF111416)
internal val NightSurface = Color(0xFF1A1E21)
internal val NightSurfaceVariant = Color(0xFF2B3034)
internal val NightText = Color(0xFFF4F1EC)
internal val NightTextMuted = Color(0xFFD5D0C9)
internal val NightBlue = Color(0xFFB9D8F2)
internal val OnNightBlue = Color(0xFF0A263B)
internal val NightBrown = Color(0xFFE6C5A8)
internal val OnNightBrown = Color(0xFF3E2E20)
internal val NightGreen = Color(0xFF88D7A8)
internal val OnNightGreen = Color(0xFF00391F)
internal val NightGreenContainer = Color(0xFF0B5330)
internal val OnNightGreenContainer = Color(0xFFB5F2CC)
internal val NightOutline = Color(0xFFAEB6BC)
internal val NightOutlineVariant = Color(0xFF3D464D)
internal val NightAlarm = Color(0xFFFFB4A8)
internal val OnNightAlarm = Color(0xFF561407)
internal val NightAlarmContainer = Color(0xFF741F29)
internal val OnNightAlarmContainer = Color(0xFFFFDADD)
